<?php

namespace Addy\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LivePageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivePageRepository extends EntityRepository
{
}
